DotNetBanky.Admin/Pages/Dashboard/CountryDetails/Index.cshtml.cs
using DotNetBanky.BLL.Services;
using DotNetBanky.Core.DTOModels.Dashboard;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SmartBreadcrumbs.Attributes;

namespace DotNetBanky.Admin.Pages.Dashboard.CountryDetails
{
    [Breadcrumb("Country Details")]
    [ResponseCache(Duration = 60, VaryByQueryKeys = new[] { "countryName" }, Location = ResponseCacheLocation.Any, NoStore = false)]
    public class IndexModel : PageModel
    {
        private readonly IDashboardService _dashboardService;

        public IndexModel(IDashboardService dashboardService)
        {
            _dashboardService = dashboardService;
        }

        public DashboardCountryDetailsDTO CountryDetails { get; set; } = null!;
        public string CountryName { get; set; } = null!;

        public async Task OnGetAsync(string countryName)
        {
            CountryName = countryName;
            CountryDetails = await _dashboardService.GetDashboardCountryDetailsAsync(countryName);
        }
    }
}

DotNetBanky.Admin/Pages/Dashboard/Index.cshtml.cs
using DotNetBanky.BLL.Services;
using DotNetBanky.Core.DTOModels.Dashboard;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SmartBreadcrumbs.Attributes;

namespace DotNetBanky.Admin.Pages.Dashboard
{
    [DefaultBreadcrumb("Dashboard")]
    public class IndexModel : PageModel
    {
        private readonly IDashboardService _dashboardService;

        public IndexModel(IDashboardService dashboardService)
        {
            _dashboardService = dashboardService;
        }

        public DashboardSummeryDTO DashboardModel { get; set; }
        public List<DashboardCountryCardDTO> DashboardCountryList { get; set; }

        public async Task OnGetAsync()
        {
            DashboardModel = await _dashboardService.GetDashboardSummeryAsync();
            DashboardCountryList = await _dashboardService.GetDashboardCountriesSummeryAsync();
        }
    }
}

DotNetBanky.Admin/Pages/Shared/Components/CountryCard/CountryCardViewComponent.cs
using DotNetBanky.Core.DTOModels.Dashboard;
using Microsoft.AspNetCore.Mvc;

namespace DotNetBanky.Admin.Pages.Shared.Components.CountryCard
{
    public class CountryCardViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(DashboardCountryCardDTO countryData)
        {
            return View(countryData);
        }
    }
}

DotNetBanky.Admin/Pages/Dashboard/Index.cshtml
@page
@model DotNetBanky.Admin.Pages.Dashboard.IndexModel
@{
    ViewData["Title"] = "Dashboard";
}

<div class="row">
    <!-- End Col -->
    <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="icon-card mb-30">
            <div class="icon success">
                <i class="fas fa-file-invoice-dollar"></i>
            </div>
            <div class="content">
                <h6 class="mb-10">Number of accounts</h6>
                <h3 class="text-bold mb-10">@Model.DashboardModel.TotalNumberOfAccounts.ToStringFormated()</h3>
            </div>
        </div>
        <!-- End Icon Cart -->
    </div>
    <!-- End Col -->
    <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="icon-card mb-30">
            <div class="icon primary">
                <i class="fa-solid fa-users"></i>
            </div>
            <div class="content">
                <h6 class="mb-10">Number of customers</h6>
                <h3 class="text-bold mb-10">@Model.DashboardModel.TotalNumberOfCustomers.ToStringFormated()</h3>
            </div>
        </div>
        <!-- End Icon Cart -->
    </div>
    <!-- End Col -->
    <div class="col-lg-4 col-md-6 col-sm-12">
        <div class="icon-card mb-30">
            <div class="icon orange">
                <i class="fa-solid fa-dollar-sign"></i>
            </div>
            <div class="content">
                <h6 class="mb-10">Sum of accounts</h6>
                <h3 class="text-bold mb-10">@Model.DashboardModel.TotalSumOfAllAccounts.ToStringCurrencyFormated()</h3>
            </div>
        </div>
        <!-- End Icon Cart -->
    </div>
    <!-- End Col -->
</div>
<div class="row">
    @foreach (var country in Model.DashboardCountryList)
    {
        @await Component.InvokeAsync("CountryCard", new { countryData = country })
    }
</div>